import houseLogo from "./assets/house_logo.jpg";
import balloonLogo from "./assets/balloon_logo.jpg";
import bellLogo from "./assets/bell_logo.jpg";
import type { ICategory, ISearchValue, IRoom, IHotel } from "./types";

export const rooms: IRoom[] = [
  {
    id: "1",
    type: "room",
    title: "Rum i Landala",
    date: "17-19 juli",
    host: "Privat värd",
    price: "Totalt 1 140 SEK",
    rating: "4,79",
    img: "/images/1.avif",
    favorite: true,
  },
  {
    id: "2",
    type: "room",
    title: "Husbåt i Göteborg",
    date: "17-21 juni",
    host: "Privat värd",
    price: "Totalt 12 353 SEK",
    rating: "4,88",
    img: "/images/2.avif",
    favorite: false,
  },
  {
    id: "3",
    type: "room",
    title: "Lägenhet i Göteborg",
    date: "11-13 sep",
    host: "Privat värd",
    price: "Totalt 3 295 SEK",
    rating: "4,95",
    img: "/images/3.avif",
    favorite: true,
  },
  {
    id: "4",
    type: "room",
    title: "Båt i Nordstaden",
    date: "5-7 juni",
    host: "Privat värd",
    price: "Totalt 4 325 SEK",
    rating: "4,93",
    img: "/images/4.avif",
    favorite: true,
  },
  {
    id: "5",
    type: "room",
    title: "Lägenhet i Göteborg",
    date: "17-21 juni",
    host: "Privat värd",
    price: "Totalt 1 765 SEK",
    rating: "5,0",
    img: "/images/5.avif",
    favorite: true,
  },
  {
    id: "6",
    type: "room",
    title: "Lägenhet i Hålltorp",
    date: "2-4 okt",
    host: "Privat värd",
    price: "Totalt 7 589 SEK",
    rating: "4,88",
    img: "/images/6.avif",
    favorite: true,
  },
  {
    id: "7",
    type: "room",
    title: "Lägenhet i Göteborg",
    date: "19-21 juni",
    host: "Privat värd",
    price: "Totalt 4 000 SEK",
    rating: "4.86",
    img: "/images/7.avif",
    favorite: false,
  },
];

export const hotels: IHotel[] = [
  {
    id: "1",
    type: "hotel",
    title: "Hotel Ronda Lesseps",
    price: "5 525 SEK Totalt",
    rating: "4,78",
    img: "/images/8.avif",
    favorite: false,
  },
  {
    id: "2",
    type: "hotel",
    title: "chic&basic Habana Hoose",
    price: "5 947 SEK Totalt",
    rating: "4,8",
    img: "/images/9.avif",
    favorite: false,
  },
  {
    id: "3",
    type: "hotel",
    title: "The Moods Oasis",
    price: "4 900 SEK Totalt",
    rating: "4,84",
    img: "/images/10.avif",
    favorite: false,
  },
  {
    id: "4",
    type: "hotel",
    title: "Arenas Atiram Hotel",
    price: "5 015 SEK Totalt",
    rating: "4,77",
    img: "/images/11.avif",
    favorite: false,
  },
  {
    id: "5",
    type: "hotel",
    title: "Hotel Casa Luz",
    price: "7 406 SEK Totalt",
    rating: "4,78",
    img: "/images/12.avif",
    favorite: false,
  },
  {
    id: "6",
    type: "hotel",
    title: "Eco-Boutique Hostal Grau",
    price: "6 798 SEK Totalt",
    rating: "4,84",
    img: "/images/13.avif",
    favorite: false,
  },
  {
    id: "7",
    type: "hotel",
    title: "H10 Marina Barcelona",
    price: "7 330 SEK Totalt",
    rating: "5,0",
    img: "/images/14.avif",
    favorite: false,
  },
];
export const categories: ICategory[] = [
  {
    id: "1",
    title: "Boenden",
    logo: houseLogo,
    new: false,
  },
  {
    id: "2",
    title: "Upplevelser",
    logo: balloonLogo,
    new: true,
  },
  {
    id: "3",
    title: "Tjänster",
    logo: bellLogo,
    new: true,
  },
];

export const searchValues: ISearchValue[] = [
  { id: "1", title: "Var", placeholder: "Sök destinationer" },
  { id: "2", title: "När", placeholder: "Lägg till datum" },
  { id: "3", title: "Vem", placeholder: "Lägg till gäster" },
];
